CREATE DATABASE IF NOT EXISTS `task-scheduler`;
USE `task-scheduler`;
CREATE TABLE IF NOT EXISTS Cin (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED') DEFAULT 'PENDING',
    last_executed TIMESTAMP NULL DEFAULT NULL,
    round_robin_index INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Din (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED') DEFAULT 'PENDING',
    last_executed TIMESTAMP NULL DEFAULT NULL,
    round_robin_index INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Cin_Din_Dependency (
    cin_id BIGINT NOT NULL,
    din_id BIGINT NOT NULL,
    PRIMARY KEY (cin_id, din_id),
    FOREIGN KEY (cin_id) REFERENCES Cin(id) ON DELETE CASCADE,
    FOREIGN KEY (din_id) REFERENCES Din(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Task_Execution_Log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_type ENUM('CIN', 'DIN') NOT NULL,
    task_id BIGINT NOT NULL,
    execution_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED') NOT NULL
);
